### ISSUE TITLE
Map events not passed properly

### ISSUE THREAD

**Issue by maceksimon** [fawmi/vue-google-maps#47]
When map is clicked the event passed into the handler function is not the GoogleMap click event but a simple PointerEvent.

See edited example:
https://stackblitz.com/edit/vue-google-maps-marker-hy9ekf?file=src/components/ComponentWithMap.vue

Expected behavior:
Handler function gets passed a GoogleMap event with properties such as latLng etc.
(This is similar to marker dragend events in a recent bugfix https://github.com/fawmi/vue-google-maps/issues/35)

Use case:
Add a marker on click/doubleclick.

Many thanks!

**Comment by hansvn** [comment]
@maceksimon I encountered the same issue.

After some digging around in the code I found that Google Maps events are only registered when you have one of the following: 
- `autobindAllEvents` set to true when you initialize the plugin
-  reference a specific event as an attribute (this happens in `src/utils/bindEvents.js`).

This means that if you want a `@click` on the map it won't register unless you also have something like `click="something"` or `:click="true"`.
Also keep in mind that the events defined in the package don't really follow Vues camelcase typing (`dblclick` and `dragend` should be all lowercase for example).
(I think the intention might have been to add a handler as an attribute instead of an event).

I'll point out two possible quick fixes: The first one does register all events defined on all components, which can lead the component into a jungle of events being fired. But being the easiest one it looks like this:
```js
app.use(VueGoogleMaps, {
    autobindAllEvents: true, // 👈👈👈
    load: {
        key: 'YOUR_API_KEY_COMES_HERE',
    },
})
```

The second option would be to add `click="something"` (make sure it's not an empty string, this would fail the validity check and not register the event).
```html
<GMapMap
      :click="yes"
      @click="onMapClicked"
  >
```

Both options shouldn't be considered as a permanent fix, Vue still fires a PointerEvent on the actual component (the container div) - though you could filter these events out.

I might open a PR tomorrow to address these issues (it's getting really late), I do have a patch available so if you want something more robust I can share that one too.

**Comment by maceksimon** [comment]
Thank you @hansvn for a great explanation! It solved the problem for me.
Second approach makes the most sense when enabling a single feature/event.
In the GMapMap, you can do:
`:click="true"` or `click="yes"`
Closing the issue.
🙏
